zuul:
    host:
        connect-timeout-millis: 60000
        socket-timeout-millis: 60000
hystrix:
    command:
        default:
            execution:
                timeout:
                    enabled: false
ribbon:
    ConnectTimeout: 60000
    ReadTimeout: 60000